language: cpp
os: linux
branches:
  only:
  - master
  - dev
jobs:
  include:
    - os: linux
      script:
        - mkdir build && cd build
        - cmake ..
        - make
    - os: osx
      osx_image: xcode10
      script:
        - mkdir build && cd build
        - cmake ..
        - make
    - os: windows
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .