# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

variables:
  build_type: Debug
  build_std: 11
  CMAKE_BUILD_PARALLEL_LEVEL: 4

strategy:
  matrix:
    Linux14:
      vmImage: 'ubuntu-latest'
    macOS17:
      vmImage: 'macOS-latest'
      build_std: 17
    macOS11:
      vmImage: 'macOS-latest'
      build_std: 11
    Windows17:
      vmImage: 'vs2017-win2016'
      build_std: 17
    Windows11:
      vmImage: 'vs2017-win2016'
      build_std: 11
pool:
  vmImage: $(vmImage)
steps:
- checkout: self
  submodules: true
- task: CMake@1
  inputs:
    cmakeArgs: .. -DCMAKE_CXX_STANDARD=$(build_std) -DCMAKE_BUILD_TYPE=$(build_type)
  displayName: 'Configure'
- script: cmake --build .
  displayName: 'Build'
  workingDirectory: build