# -*- mode: yaml -*-

parameters:
- name: UPLOAD_PACKAGES
  type: string
  default: 'False'

jobs:
- job: conda_osx64
  pool:
    vmImage: macOS-latest
  strategy:
    matrix:
      osx_64:
        CONFIG: osx_64
        UPLOAD_PACKAGES: ${{ parameters.UPLOAD_PACKAGES }}
  timeoutInMinutes: 360

  steps:
  - script: |
      export CI=azure
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)