# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-
parameters:
- name: UPLOAD_PACKAGES
  type: string
  default: 'False'

jobs:
- job: conda_win64
  pool:
    vmImage: $(imageName)
  strategy:
    matrix:
      vs2019:
        imageName: windows-2019
        CONFIG: win_64
        UPLOAD_PACKAGES: ${{ parameters.UPLOAD_PACKAGES }}
  timeoutInMinutes: 360
  variables:
    CONDA_BLD_PATH: D:\\bld\\

  steps:
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: 'python=3.6 conda-build conda "conda-forge-ci-setup=3" anaconda-client pip' # Optional
        installOptions: "-c conda-forge"
        updateConda: true
      displayName: Install conda-build and activate environment

    - script: set PYTHONUNBUFFERED=1
      displayName: Set PYTHONUNBUFFERED

    # Configure the VM
    - script: |
        call activate base
        setup_conda_rc .\ ".\recipe" .\.ci_support\%CONFIG%.yaml
      displayName: conda-forge CI setup

    # Configure the VM.
    - script: |
        set "CI=azure"
        call activate base
        run_conda_forge_build_setup
      displayName: conda-forge build setup

    - script: |
        call activate base
        conda.exe build "recipe" -m .ci_support\%CONFIG%.yaml
      displayName: Build recipe
      env:
        PYTHONUNBUFFERED: 1

    - script: |
        set "GIT_BRANCH=%BUILD_SOURCEBRANCHNAME%"
        set "FEEDSTOCK_NAME=%BUILD_REPOSITORY_NAME:*/=%"
        call activate base
        upload_package  .\ ".\recipe" .ci_support\%CONFIG%.yaml
      displayName: Upload package
      env:
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      condition: and(succeeded(), not(eq(variables['UPLOAD_PACKAGES'], 'False')))