# -*- mode: yaml -*-
parameters:
- name: UPLOAD_PACKAGES
  type: string
  default: 'False'

jobs:
- job: conda_linux64
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64:
        CONFIG: linux_64
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        UPLOAD_PACKAGES: ${{ parameters.UPLOAD_PACKAGES }}
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)