name: Binary (Debug)

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        required: true
        default: macos-latest
      compiler:
        description: 'Complier'
        required: true
        default: clang++

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_BUILD_PARALLEL_LEVEL: 8

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}

    steps:
    - name: Input
      run: echo "${{ github.event.inputs.os }} ${{ github.event.inputs.compiler }}"

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install libomp (macOS)
      if: github.event.inputs.os == 'macos-latest'
      run: brew install libomp
      #run: curl -LO https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/libomp.rb && brew reinstall --build-from-source --formula ./libomp.rb
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      env:
        CXX: ${{ github.event.inputs.compiler }}
      run: cmake $GITHUB_WORKSPACE -DCMAKE_CXX_COMPILER=${{ github.event.inputs.compiler }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_STANDARD=11
      
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE