name: Build

on:
  push:
    branches: [ master, v2 ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  MAKEFLAGS: "-j2"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_STANDARD=11

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
      
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        retention-days: 1
        path: |
          ${{github.workspace}}/build/**/Scaffolder
          ${{github.workspace}}/build/**/SliceTest
          ${{github.workspace}}/build/**/Scaffolder.exe
          ${{github.workspace}}/build/**/SliceTest.exe
          ${{github.workspace}}/build/**/*.dll
          ${{github.workspace}}/build/**/*.pdb
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ubuntu-latest
          path: ubuntu

      - uses: actions/download-artifact@v2
        with:
          name: macos-latest
          path: macos

      - uses: actions/download-artifact@v2
        with:
          name: windows-latest
          path: windows 

      - name: List files
        run: ls -R
        
      - uses: actions/upload-artifact@v2
        with:
          name: bin64
          path: ${{github.workspace}}/**

      - name: Upload Release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'release'
        with:
          artifacts: bin64
          token: ${{ secrets.GITHUB_TOKEN }}
