name: PyPI Wheels

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload to PyPI?'
        required: false
        default: "false"

jobs:
  build_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        persist-credentials: false # Highly recommended as a good security practice to not store credentials in disk, unless you need this for your specific use case

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v7
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
          - os: windows-latest
            arch: AMD64
          - os: macos-15-intel
            arch: x86_64
          - os: macos-15
            arch: arm64
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: Setup libomp (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install libomp
        BREW_PREFIX=$(brew --prefix libomp)
        echo "LDFLAGS=-L${BREW_PREFIX}/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I${BREW_PREFIX}/include" >> $GITHUB_ENV
        echo "OpenMP_ROOT=${BREW_PREFIX}" >> $GITHUB_ENV
        echo "MACOSX_DEPLOYMENT_TARGET=15.0" >> $GITHUB_ENV

    - name: Build wheels
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_BUILD: "cp311-* cp312-* cp313-* cp314-*"
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_TEST_COMMAND: python {project}/src/python/test.py
        CIBW_TEST_REQUIRES: numpy
        CIBW_SKIP: "pp* *-musllinux*"
        
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl

  pypi-publish:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.upload == 'true') || github.ref_type == 'tag'
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v7
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
      with:
        skip-existing: true