name: Manually Build Wheels

on:
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload to PyPI?'
        required: false
        default: false

env:
  CIBW_TEST_COMMAND: python {project}/src/python/test.py
  CIBW_TEST_REQUIRES: numpy
  CIBW_TEST_SKIP: cp310-macosx_x86_64

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2

    - name: Install deps
      run: python -m pip install twine build

    - name: Build SDist
      run: python -m build -s

    - name: Check metadata
      run: twine check dist/*

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install libomp and openblas for macos
      if: matrix.os == 'macos-latest'
      run: |
        brew install libomp
        brew install openblas

    - name: Build wheel
      uses: pypa/cibuildwheel@v2.1.1
      env:
        # Python 2.7 on Windows requires a workaround for C++11 support,
        # built separately below
        CIBW_SKIP: pp* cp27* *-win32 *-manylinux_i686 *-manylinux_aarch64 *-manylinux_ppc64le *-manylinux_s390x

    - name: Show files
      run: ls -lh wheelhouse
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl

  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event.inputs.upload != false

    steps:
    - uses: actions/setup-python@v2

    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}